### ISSUE TITLE
英伟达串流的虚拟Xbox 360手柄转换成DS4后异常！

### ISSUE THREAD

**Issue by Sskra** [micro-artwork/xi2ds#1]
虚拟X360手柄转换成DS4后，在双人成行中会识别成两个手柄(一个DS4和一个X360)同时输入！

**Comment by micro-artwork** [comment]
@Sskra XI2DS cannot occupy and read Xinput state exclusively. PSRP ignores Xinput state, so XI2DS is suitable for PSRP only.

**Comment by Sskra** [comment]
Thanks.明白了！

**Comment by Sskra** [comment]
谢谢，明白了，这个可能是屏蔽手柄未成功！经过测试，物理的Xbox one手柄转换成DS手柄后，双人成行只能识别到DS手柄，所以物理的手柄就能正常屏蔽！这个可能是VIGEM的问题！如此看来，XI2DS差一点就可以实现其他场景了！
