### ISSUE TITLE
Can't Install xi2ds

### ISSUE THREAD

**Issue by pcwizard7** [micro-artwork/xi2ds#4]
I have .NET Runtime and Desktop  .NET Runtime installed, but it still said to download and install it

**Comment by micro-artwork** [comment]
Could you check installed .NET runtime versions?

1) win + r 
2) cmd
3) dotnet --info

**Comment by pcwizard7** [comment]
global.json file:
  Not found

Host:
  Version:      6.0.10
  Architecture: x64
  Commit:       5a400c212a

.NET SDKs installed:
  No SDKs were found.

.NET runtimes installed:
  Microsoft.NETCore.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Download .NET:
  https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
  https://aka.ms/dotnet/runtimes-sdk-info

**Comment by micro-artwork** [comment]
Please install dotnet desktop runtime 5.x version and retry.

https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-5.0.17-windows-x64-installer?cid=getdotnetcore

**Comment by pcwizard7** [comment]
I had v6 installed and nothing but v5 seems to work, wired
