### ISSUE TITLE
Cant get to work on the ROG Ally

### ISSUE THREAD

**Issue by jblanc88** [micro-artwork/xi2ds#5]
I know this might be a longshot but I cant get this to work on the ROG Ally. I run the program and then click connect and then run remote play but i get no input from the ALLY. I then click disconnect and it seems like works for 1 input. I even set the ally to Controller mode and still doesnt work.

**Comment by micro-artwork** [comment]
Since PSRP was updated to v6, the virtual driver (ViGEmBus) used as the main library has not been working, and at this time, normal operation may not be possible without driver improvements.

For more information, please see:
https://github.com/ViGEm/ViGEmBus/issues/172
